import streamlit as st
import torch
import torch.nn.functional as F
import pickle

from torch_geometric.nn import SAGEConv

class GraphSAGE(torch.nn.Module):

    def __init__(self, in_channels, hidden):
        super().__init__()

        self.conv1 = SAGEConv(
            in_channels,
            hidden
        )

        self.conv2 = SAGEConv(
            hidden,
            hidden
        )

    def encode(
        self,
        x,
        edge_index
    ):

        x = self.conv1(
            x,
            edge_index
        )

        x = F.relu(x)

        x = self.conv2(
            x,
            edge_index
        )

        return x


movie_mapping = pickle.load(
    open(
        "movie_mapping.pkl",
        "rb"
    )
)

movie_titles = pickle.load(
    open(
        "movie_titles.pkl",
        "rb"
    )
)

movie_genres = pickle.load(
    open(
        "movie_genres.pkl",
        "rb"
    )
)

x = torch.load(
    "node_features.pt"
)

edge_index = torch.load(
    "edge_index.pt"
)

model = GraphSAGE(
    x.shape[1],
    64
)

model.load_state_dict(
    torch.load(
        "graphsage.pt",
        map_location="cpu"
    )
)

model.eval()

with torch.no_grad():

    embeddings = model.encode(
        x,
        edge_index
    )

movie_names = sorted(
    movie_titles.values()
)

title_to_id = {
    v:k
    for k,v in movie_titles.items()
}

st.set_page_config(
    page_title="Movie Recommender",
    layout="wide"
)

st.title(
    "Graph Neural Network Movie Recommender"
)

st.write(
    "Choose two movies you like and receive recommendations."
)

movie1 = st.selectbox(
    "Movie 1",
    movie_names
)

movie2 = st.selectbox(
    "Movie 2",
    movie_names,
    index=1
)

if st.button(
    "Recommend Movies"
):

    movie1_id = title_to_id[movie1]
    movie2_id = title_to_id[movie2]

    movie1_node = movie_mapping[movie1_id]
    movie2_node = movie_mapping[movie2_id]

    profile_embedding = (
        embeddings[movie1_node]
        +
        embeddings[movie2_node]
    ) / 2

    selected_genres = set(
        movie_genres[movie1_id]
        +
        movie_genres[movie2_id]
    )

    recommendations = []

    for movie_id,movie_node in movie_mapping.items():

        if movie_id in [
            movie1_id,
            movie2_id
        ]:
            continue

        movie_embedding = embeddings[
            movie_node
        ]

        similarity = F.cosine_similarity(
            profile_embedding.unsqueeze(0),
            movie_embedding.unsqueeze(0)
        ).item()

        recommendations.append(
            (
                movie_id,
                similarity
            )
        )

    recommendations.sort(
        key=lambda x:x[1],
        reverse=True
    )

    top_movies = recommendations[:10]

    st.subheader(
        "Recommended Movies"
    )

    for rank,(movie_id,score) in enumerate(
        top_movies,
        start=1
    ):

        title = movie_titles[movie_id]

        rec_genres = set(
            movie_genres[movie_id]
        )

        shared = selected_genres.intersection(
            rec_genres
        )

        overlap = int(
            (
                len(shared)
                /
                max(
                    len(selected_genres),
                    1
                )
            )
            *100
        )

        top_genres = list(shared)

        if len(top_genres) >= 2:

            genre_text = (
                top_genres[0]
                +
                " and "
                +
                top_genres[1]
            )

        elif len(top_genres) == 1:

            genre_text = top_genres[0]

        else:

            genre_text = "similar"

        percentile = max(
            1,
            int(
                (1-score)
                *100
            )
        )

        st.markdown(
            f"""
### {rank}. {title}

**Similarity Score:** {score:.3f}

{overlap}% genre overlap with your selected movies.

Users who enjoy {genre_text} content frequently interact with similar titles.

This recommendation ranks among the top {percentile}% highest-scoring candidates generated by the Graph Neural Network.
"""
        )

        st.divider()